### ISSUE TITLE
obsolete directories

### ISSUE THREAD

**Issue by alexmyczko** [JvanKatwijk/eti-stuff#33]
can they be removed and a release be made?

since dablin author support eti-cmdline now, i'd like to rather package eti-cmdline for debian than dabtools.

**Comment by andimik** [comment]
It always has been supported, but basicmaster added it in the readme ;-)

**Comment by basicmaster** [comment]
Well, it has been supported as any other possible ETI stream source, but the support @alexmyczko refers to is the channel switching.

**Comment by andimik** [comment]
Ok. Stefan, you are right :grinning:
